version: "3.8"

services:
  vpn-client:
    image: ghcr.io/relybytes/vpn-website-proxy:latest
    cap_add:
      - NET_ADMIN
    ports:
      - "18080:18080"
    environment:
      - VPN_URL=
      - VPN_USER=
      - VPN_PASS=
      - PROXY_PASS_URL=
      - PROXY_BASE_URL=
      - PROXY_LISTEN_PORT=18080
