name: Docker Image CI

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["main"]

env:
  DOCKER_REGISTRY: ghcr.io/relybytes/vpn-website-proxy

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        env:
          REGISTRY: ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Define variables
        id: vars
        run: |
          echo "date=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_OUTPUT
          echo "short_sha=$(echo ${{ github.sha }} | cut -c 1-7)" >> $GITHUB_OUTPUT
          echo "branch_name=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          echo "tag_name=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
      - name: Build and push Docker image for Tags
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}:${{ steps.vars.outputs.tag_name }}
            ${{ env.DOCKER_REGISTRY }}:latest
      - name: Build and push Docker image for Branches
        if: startsWith(github.ref, 'refs/heads/')
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}:latest
            ${{ env.DOCKER_REGISTRY }}:${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.short_sha }}
            ${{ env.DOCKER_REGISTRY }}:${{ steps.vars.outputs.branch_name }}-latest
